### ISSUE TITLE
 When you stop the container, it does not start again. Error in mysql

### ISSUE THREAD

**Issue by markCornejo** [TonisOrmisson/dev-lemp#1]
I execute

docker run -d -i --network=bridge -v D:/Proyectos/trabajos/contenedores/prueba1:/var/www/html/  --name containername -p 8888:80 tonisormisson/dev-lemp

It works correctly, but when I stop the container **docker stop containername**. And I return it to start the following.

PS C:\Users\user> docker start containername -a
Starting mysql
Starting MySQL database server mysqld
   ...fail!
Failed to start mysql: 1

And logs
PS C:\Users\user> docker logs containername
Starting mysql
Starting MySQL database server mysqld
   ...done.
Starting PHP-fpm
Starting Selenium ...
Starting nginx ....
Starting mysql
Starting MySQL database server mysqld
   ...fail!
Failed to start mysql: 1
Starting mysql
Starting MySQL database server mysqld
   ...fail!
Failed to start mysql: 1
Starting mysql
Starting MySQL database server mysqld
Starting mysql
Starting MySQL database server mysqld
   ...fail!

**Comment by TonisOrmisson** [comment]
Thanks for reporting. 

I tested it for a while and managed to reproduce the starting failure after some stops & starts. 
Logs show that mysql was unable to start since there was already a process existing using the mysql.sock. I have removed the lines from start.sh exiting the program if service will not start - it just might already be running. 
Anyway there is a new release hopefully fixing that issue
